### ISSUE TITLE
Question how to map dynamic ip in to manifest of neighbor job

### ISSUE THREAD

**Issue by Alexvianet** [bosh-prometheus/prometheus-boshrelease#189] opened 2018-04-16 07:48 UTC
HI sorry for disturb, can someone help how to map(link) dynamic ip of  neighbor job in to manifest.
I have fond hot to map static_ips: "(( jobs.postgres.networks.default.static_ips.[0] ))" but can't get how to map dynamic =(
Help please

**Comment by Alexvianet** [comment] 2018-04-16 07:53
also, a know how to map dynamic IP in templates but I need to do such in the manifest like:
```
    properties:
      alertmanager:
        receivers:
          - name: slack-receiver
            webhook_configs:
              - url: (( concat "http://" jobs.prom2teams.networks.dynamic.[0] ":8089/v2/Connector" ))
                send_resolved: true
```

**Comment by Alexvianet** [comment] 2018-04-16 08:39
![screenshot from 2018-04-16 11-38-13](https://user-images.githubusercontent.com/17483589/38798626-c009c5ee-416a-11e8-8954-9c02a2269ad5.png)
try to do that

**Comment by Alexvianet** [comment] 2018-04-16 08:40
webhook_config: 
url is not working =(

**Comment by frodenas** [comment] 2018-04-16 09:27
And the problem is that `spruce` is not resolving the ips? have you tried asking at the `spruce` repo?

**Comment by Alexvianet** [comment] 2018-04-16 09:36
- $.instance_groups.alertmanager.properties.alertmanager.receivers.slack-receiver.webhook_configs.0.url: Unable to resolve `jobs.prom2teams.networks.dynamic.0`: `$.jobs` could not be found in the datastructure

some wrong variable as i see, i do not know what is correct =(

**Comment by Alexvianet** [comment] 2018-04-16 09:36
i ll try

**Closed** 2018-04-16 09:51 UTC
