### ISSUE TITLE
Apps dashboard now working on Grafana With Prometheus V18.0.0

### ISSUE THREAD

**Issue by cfmagnum** [bosh-prometheus/prometheus-boshrelease#144] opened 2017-12-12 12:26 UTC
Hi @frodenas 
We are writing you again, since we landed up in same trouble for grafana Apps dashboard not working as expected. After deployment lets say a week ago it was working fine. Now since last 3 days it stopped showing the Apps: latency, Apps: System, Apps: Request. We found some logs but it did not helped much Attaching the grafana vm logs and prometheus vm logs. Also up till version 18.0.0 all the changes were covered in CF side and Prometheus side.
[prometheus-stderr.txt](https://github.com/bosh-prometheus/prometheus-boshrelease/files/1551443/prometheus-stderr.txt)
[grafana-logs.txt](https://github.com/bosh-prometheus/prometheus-boshrelease/files/1551444/grafana-logs.txt)

Also attaching my Prometheus manifest here.
[prometheus-deployment-yml.txt](https://github.com/bosh-prometheus/prometheus-boshrelease/files/1551533/prometheus-deployment-yml.txt)

Please do let me know if anything else related is required. Awaiting for your reply

Thanks

**Comment by frodenas** [comment] 2017-12-14 06:16
Please check the `firehose_exporter` logs for any error. If the metrics were reported and then they disappear, this must be a problem with the metrics collector.

**Comment by cfmagnum** [comment] 2017-12-14 12:45
Hello @frodenas 
Gone to firehose_exporter to check the metrics but did not found anything related.
But there are few issue related to access in cf_exporter error logs.
Attaching the same files cf_exporter and firehose_exporter logs.
[cf_exporter logs.txt](https://github.com/bosh-prometheus/prometheus-boshrelease/files/1559193/cf_exporter.logs.txt)
![firehose_exporter logs](https://user-images.githubusercontent.com/13657881/33992988-acf7c80a-e0fa-11e7-946d-bb29bcfa72f0.PNG)

Can anything be concluded by the above logs.

Thanks,

**Comment by frodenas** [comment] 2017-12-14 17:07
The error message `oauth2: cannot fetch token: 401 Unauthorized` at the `cf_exporter` logs means that it was unable to fetch data from the CF CC b/c the UAA token expired.

This usually happens when you're using a `username` and `password` for authentication instead of using a `client-id` and `client-secret`. Can you please check your CF deployment manifest to see what method the `cf_exporter` is using to authenticate?

**Comment by cfmagnum** [comment] 2017-12-15 09:36
@frodenas cf_exporter uses username and password as an authentication. But this really impact the data not to populate on the apps dashboard of grafana.

**Comment by frodenas** [comment] 2017-12-15 16:10
Those dashboards use data from the `cf_exporter`. You can just try to restart the exporter and see if now data is populated.

**Comment by cfmagnum** [comment] 2017-12-28 15:29
Hello @frodenas 
Thanks for the above comment, after doing the process restart in exporter VM we get the Prometheus working for a particular time frame(in our case the cf admin creds and time expire is mentioned). Once the token expires the same issue jumps in. My question to you is can we have a permanent solution on this, like if we can increase the time frame or by any other mean.

Also, I am facing the below issue while restarting the process in exporter vm.
[Exporter.txt](https://github.com/bosh-prometheus/prometheus-boshrelease/files/1591481/Exporter.txt)
Is the above issue due to space or token expires?

Thanks

**Comment by frodenas** [comment] 2017-12-28 15:55
@cfmagnum The "permanent" solution is to switch to use an UAA client instead of a user.

Create a new UAA client using the [prometheus-uaa-clients.yml](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/operators/cf/add-prometheus-uaa-clients.yml) op file as an example, and then configure the `cf_exporter` to use the new credentials (`cf_exporter.cf.client_id` and `cf_exporter.cf.client_secret`).

The `read: connection reset by peer` error message is mostly due to a low HAProxy read timeout.

**Comment by cfmagnum** [comment] 2018-01-02 11:35
Hello @frodenas 

We resolved the issue for token expire by adding the UAA client. Currently stuck with bosh dashboard issue where bosh:jobs and overview are not working as expected.
As you suggested in https://github.com/bosh-prometheus/prometheus-boshrelease/issues/132  we have switched to bosh exporter and the properties which we added in prometheus manifest is below:
 **prometheus:
      bosh_exporter:
        metrics:
          environment: dev
        bosh:
          url: https://*******:25**
          username: *****
          password: ***** **

Still the bosh dashboard is not visible. Can you suggest what else we are missing in here.

Thanks in advance

**Comment by frodenas** [comment] 2018-01-03 11:52
When you say *bosh dashboard issue where bosh:jobs and overview are not working as expected*, what do you mean? Dashboards don't appear on the dashboard lists? Are those dashboards empty?

**Comment by cfmagnum** [comment] 2018-01-03 14:18
Hello @frodenas ,
Yes, you got it correct bosh: jobs and overview are empty. Data is not populated.
Attaching the screenshot for the same.
![untitled](https://user-images.githubusercontent.com/13657881/34523307-eaf28312-f0bc-11e7-8405-c8c7b192713a.jpg)
![screen shot 01-03-18 at 07 38 pm](https://user-images.githubusercontent.com/13657881/34523816-0630cdbc-f0bf-11e7-9ff8-289e709d79ea.PNG)

Let me know if anything else is required.

**Comment by frodenas** [comment] 2018-01-03 23:49
Check your manifest, do you have a `prometheus.scrape_configs` property with
```
- job_name: bosh
  scrape_interval: 2m
  scrape_timeout: 1m
  static_configs:
  - targets:
    - <bosh exporter ip address>:9190
```

**Comment by cfmagnum** [comment] 2018-01-08 11:39
Hello @frodenas 
Sorry for the delay in response. We don't have that scrape_config in our prometheus deployment.
Do you want me to put that, if yes we did tried it and the deployment failed with the port error.

Other than that attaching my bosh manifest and prometheus manifest just to be sure that what we can do, so that our bosh:jobs and overview start working.
[Prometheus Manifest.txt](https://github.com/bosh-prometheus/prometheus-boshrelease/files/1611366/Prometheus.Manifest.txt)
[Bosh Manifest.txt](https://github.com/bosh-prometheus/prometheus-boshrelease/files/1611367/Bosh.Manifest.txt)

Thanks,

**Comment by frodenas** [comment] 2018-01-10 11:03
@cfmagnum You're NOT deploying the `bosh_exporter`. You need to add it to your prometheus deployment, otherwise it will NOT scrape bosh metrics.

**Comment by cfmagnum** [comment] 2018-01-15 07:45
Hi @frodenas We added the bosh exporter properties in prometheus deployment. Now as per our release we upgraded CF to 281 and Prometheus on same version as before i.e. 18.0.0. 
The Entire grafana dashboard is not visible also i saw failure logs in grafana i.e.  
**"t=2018-01-15T06:33:01+0000 lvl=eror msg="Plugins: Failed to load plugin json file: /var/vcap/data/packages/grafana_plugins/bb0b22d1a59a7aeb220d79dde370a92003edcf15/worldping-app/dist/grafana-worldmap-panel/plugin.json,  err: Plugin with same id already exists"**

I tried to kill this process and also tried to recreate the grafana vm, but still the issue persist.
Can you let me know what went wrong here.
Do let me know if you need entire logs on grafana vms

Attaching the snap of grafana dashboard for ref:
![grafana](https://user-images.githubusercontent.com/13657881/34931692-02a441de-f9f6-11e7-9bda-47bbe2d6305b.PNG)

**Comment by cfmagnum** [comment] 2018-01-15 13:15
We found the solution for the above issue. It was UUID which got changed and hence the dashboard was not reflected coz the new UUID is not included in the manifest. Now we landed on the same page with bosh:jobs and overview after adding the bosh_exporter in properties below the grafana. Still unable to fetch the bosh data.
Do let us know if we have any other solution that can be applied or we missed anything while inline the bosh_exporter in the manifest.
Below is the sanitized manifest for prometheus.

[new 6.txt](https://github.com/bosh-prometheus/prometheus-boshrelease/files/1631722/new.6.txt)

**Comment by frodenas** [comment] 2018-01-24 03:47
You also need to add the `bosh_exporter` template to the `prometheus` vm. Also, the error comes from the `scrape_config` section at `/var/vcap/jobs/prometheus/config/prometheus.yml`, maybe the comment you added are not well formatted.

**Comment by benjaminguttmann-avtq** [comment] 2018-01-25 15:58
In addition to that in the comment in should be 'static_configs' instead of 'static_config'. That is also said in the log you just provided.

**Comment by lordcf** [comment] 2018-01-30 05:02
@frodenas @benjaminguttmann-avtq thank you for the prompt response.
After changing the templates and scrape config in prometheus manifest we tried to deploy it again, the deployment completed successfully however the prometheus vm is failing. The bosh_exporter error shows up as failed with the following logs
**time="2018-01-30T04:53:25Z" level=error msg="Error creating BOSH Client: Fetching info: Performing request GET 'https://10.1.1.4:25555/info': Performing GET request: Retry: Get https://10.1.1.4:25555/info: x509: cannot validate certificate for 10.1.x.x because it doesn't contain any IP SANs" source="bosh_exporter.go:322"**

There is CA certs issue as well which i suppose linked with bosh_exporter. I tried manually giving certs as **ca_certs= default ca** or 
**tls_config:
          insecure_skip_verify: true**
but no luck.

My question is can we put manually certs or some other way to skip the certs part like mentioning any parameter in the manifest. Also the port 9190 is open with two way communication at my VPC level i.e. bosh to promtheus and v-a-v.

FYI
**- job_name: bosh
      scrape_interval: 60s
      scrape_timeout: 60s
      static_configs:
      - targets:
        - 10.1.1.4:9190
       # in_cluster: true
        tls_config:
          insecure_skip_verify: true**


 **bosh_exporter:
    metrics:
      environment: dev
    bosh:
      url: https://10.1.1.4:25555
      username: admin
      password: LT3ZUkEWqrCV65A2JFvM9xzSFg!OPD
      ca_certs:** 

Awaiting for your response.

**Comment by frodenas** [comment] 2018-01-30 22:43
The problem is not in the prometheus scrape config, the problem is at the bosh exporter. The error message `x509: cannot validate certificate for 10.1.x.x because it doesn't contain any IP SANs` means that the certificate used when the director was deployed does NOT contain the 10.1.x.x IP address as the hostname or alternate names. There's currently no way to skip that SSL verification, as the bosh library used to connect to the director does not allow that option.

**Comment by frodenas** [comment] 2018-02-27 23:19
Closing this, please reopen if the problem still persists.

**Closed by frodenas** 2018-02-27 23:19 UTC
Labels: bug
