### ISSUE TITLE
Grafana dashboard for cloud foundry not showing data

### ISSUE THREAD

**Issue by sfrancies** [bosh-prometheus/prometheus-boshrelease#305] opened 2019-05-09 05:49 UTC
Grafana dashboard for cloud foundry is not showing data, with the latest prometheus-boshrelease.
Issue with the query using $bosh_deployment variable

avg(firehose_container_metric_cpu_percentage{environment=~"$environment",bosh_deployment=~"$bosh_deployment",application_id=~"$cf_application_id"})

While the $bosh_deployment returns value "cf"  but the firehose exporter data has full deployment name for cf " cf-7b89e17fb2ea1a2848ac "  below query form prometheus 

firehose_container_metric_cpu_percentage{application_id="004d6edb-5ade-4cfc-938b-fa4024d5e314",bosh_deployment="cf-7b89e17fb2ea1a2848ac",bosh_job_id="2311070e-c5f5-4cdb-92c0-06659690192d",bosh_job_ip="10.242.100.54",bosh_job_name="diego_cell",environment="eu-prod-blue",instance="localhost:9186",instance_index="0",job="firehose_exporter",origin="rep"}

If I remove the bosh_deployment=~"$bosh_deployment" from the grafana dashboard query I get the graph neat. but I am not able to save this dasboard.

We are using PCF PAS 2.4 version. maybe with the latest version bosh_deployment name emitted by firehose is changed to use full value instead of just cf ?

**Comment by benjaminguttmann-avtq** [comment] 2019-05-09 07:11
Hi @sfrancies ,

I am not exactly sure which dashboard you mean, but I guess it is related to the Diego Cell ones.
Could you please check which value could be found in the metric `firehose_value_metric_rep_capacity_total_containers` for `bosh_deployment`. Does it say `cf` or `cf-xy`

Maybe there was some change for the `metron_deployment_name` mentioned [here](https://github.com/bosh-prometheus/prometheus-boshrelease#monitoring-cloud-foundry).

**Comment by sfrancies** [comment] 2019-05-09 19:08
Hi, 
I am talking about Cloudfoundry dashboard specific to Apps:System , Apps: Requests , Apps: Latency ...

from prometheus when I query I get bosh deployment value as cf-xxx

firehose_value_metric_rep_capacity_total_containers{bosh_deployment="cf-7b89e17fb2ea1a2848ac"

**Comment by benjaminguttmann-avtq** [comment] 2019-05-10 06:44
@sfrancies : Thanks in that case you need to check this metric for the bosh_deployment name 

`cf_application_info` as the value for the deployment drop-down comes from there.

**Comment by sfrancies** [comment] 2019-05-10 18:36
Yes, the bosh_deployment variable is queried as label_values(cf_application_info{environment=~"$environment"}, deployment)
which returns value as "cf", which used to work before but not with the latest version firehose metrics return cf-xxx for bosh_deployment.

Please help me on how to fix this ? Do we need to update the grafana dashboard ?

**Comment by benjaminguttmann-avtq** [comment] 2019-05-17 05:54
@sfrancies , no it should be easier than that. 
Please try to set the variable `metron_deployment_name` (https://github.com/bosh-prometheus/prometheus-boshrelease/blob/fe5c56b82ec68d947d81dd8e39a76a83c34a03d1/manifests/operators/monitor-cf.yml#L16) to the name of your cf deployment like `cf-xxx`. Afterwards deploy again.

If this solves the issue it might be necessary to adjust the README to address this as the current behavior changed.

**Comment by sfrancies** [comment] 2019-05-21 06:55
Hi Benjamin,
Yes, after setting variable metron_deployment_name to cf-xxx , I am able to get the graphs in Grafana dashboard.

Is there a way to pull cf deployment ( cf-xxx ) name directly with a variable instead of manually updating it in our param file ?
I see bosh deployments variable in BOSH: deployments dashboard return all deployment names correct.

**Comment by benjaminguttmann-avtq** [comment] 2019-05-21 06:56
@sfrancies , thanks for your feedback. Not sure if that is possible. The problem is, the value was more or less static before now it seems to be installation related...

**Comment by sfrancies** [comment] 2019-05-21 15:57
Thanks Benji,
Pivotal in the release notes mentioned about this breaking change from PCF 2.4

PAS v2.4 introduced the use of cf-GUID as the value for the deployment in metrics. For more information, see Uniquely Identify Metrics by Tile.

PAS v2.4 also included the option to override this value back to cf, which was used in previous versions. However, PAS v2.5 removes this override option.

To upgrade successfully, the Use “cf” as deployment name in emitted metrics instead of unique name option in the Advanced Features pane of the PAS tile must be deselected.

If you have scripts that rely on metrics with cf as the value for deployment, your scripts may break when upgrading to PAS v2.5.

**Comment by daichi703n** [comment] 2019-06-03 03:42
Hi, @benjaminguttmann-avtq , @sfrancies 

I had similar issue, and created PR. (not yet merged)

https://github.com/bosh-prometheus/prometheus-boshrelease/pull/285 Enable monitor CF Isolation Segment on CF/Apps dashboard

Title scoped "Isolation Segment", but this change will be applied to this issue.

> Because `application_id` in `firehose_container_metric_cpu_percentage` (and the other) is **UUID**, `bosh_deployment` is unnecessary for collectiong metrics query. (only used for templating)

How do you think?

**Comment by sfrancies** [comment] 2019-08-07 21:06
Yes I agree with that @daichi703n , we don't need bosh_deployment for cf apps dashboard

**Comment by benjaminguttmann-avtq** [comment] 2021-09-14 11:52
@sfrancies can you try do adjust the `metron_deployment_name` when you deploy prometheus to match the name of the cf deployment (the information you can see in the firehose metric) and check if that helps to improve your situation.

**Closed** 2022-08-12 11:04 UTC
